#!/usr/bin/env bash

[ -f "$HOME/.md2gdrc" ] && source "$HOME/.md2gdrc"

import () {
  # If reference file exists, include it as a pandoc argument
  [ -f "$MD2GD_DIR/reference.docx" ] && REFERENCE_DOCX="--reference-docx=$MD2GD_DIR/reference.docx"

  temp_file=$(mktemp "$1.docx")

  pandoc "$1" --from markdown --to docx "$REFERENCE_DOCX" -o "$temp_file"

  [ $? -ne 0 ] && { printf "md2gd: Conversion failed\n"; rm "$temp_file"; exit 1; }

  printf "please import $temp_file from your browser\n"

  exit 0
}

usage () {
  cat <<EOF
usage:
  md2gd import <file>
EOF
}

assert_dep () {
  type "$1" > /dev/null 2>&1
  [ $? -eq 0 ] && return
  [ $? -ne 0 ] && { printf "dependency %s not found\n" "$1"; exit 1; }
}

assert_dep 'pandoc'

case $1 in
  import) shift; import "$@";;
  *) usage; exit 1;;
esac
